name: 'Label Actions'

on:
  issues:
    types: [labeled, unlabeled]
  pull_request:
    types: [labeled, unlabeled]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/label-actions@v2
        with:
          github-token: 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
          config-path: '.github/label-actions.yml'
          process-only: ''
