
name: PR-Test 

on:
  pull_request:
    types: [ labeled,unlabeled ]

jobs: 
  auto-commit-test:
    runs-on: ubuntu-latest
    steps:
      - name: MainBranch Checkout
        uses: actions/checkout@v2
      
      - uses: DamianReeves/write-file-action@v1.0
        with:
          path: Dockerfile
          contents: |
            pr is merged
          write-mode: append
      - name: Test
        run: |
          ls
          cat Dockerfile
      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v2.3.0
        with:
          commit_message: Apply changes
          branch: main
          file_pattern: Dockerfile
        env:
          GITHUB_TOKEN: ${{ secrets.NSLHB_TEST_TOKEN }} 
        
      - uses: DamianReeves/write-file-action@v1.0
        with:
          path: Dockerfile
          contents: |
            pr is merged 2
          write-mode: append
      - name: test2
        run: |
          git add Dockerfile
          git commit -m "testing"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.NSLHB_TEST_TOKEN }}   
             
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Step 1 - MainBranch Checkout
#        uses: actions/checkout@v2
#     
#      - name: Step 2 - JDK SETUP
#        uses: actions/setup-java@v2
#        with:
#          java-version: '15'
#          distribution: 'adopt'      
#      
#      - name: Set up Maven
#        uses: stCarolas/setup-maven@v4
##        with:
 #           maven-version: 3.8.1 
        
#      - name: Run Test
#        run: |
#          mvn test
#        
#      - uses: mshick/add-pr-comment@v1
#        if: always() && failure() && !${{ github.event.label.name == 'do-not-merge/hold' }}
#        with:
#          message: |
#            Maven Test Failed 
#            /hold
#          repo-token: ${{ secrets.NSLHB_TEST_TOKEN }}
#          repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
#          allow-repeats: true
#          
#      - uses: mshick/add-pr-comment@v1
#        if: always() && success() && ${{ github.event.label.name == 'do-not-merge/hold' }}
#        with:
#          message: |
#            Maven Test Passes 
#            /remove-hold
#          repo-token: ${{ secrets.NSLHB_TEST_TOKEN }}
#          repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
#          allow-repeats: true   
#          

          
