name: PROW-Test 

on:
  pull_request:
    types: [opened]

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      test: ${{ steps.test-job.outputs.matrix }}
    steps:
      - uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: '/ok-to-test'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.NSLHB_TEST_TOKEN }}'
      - name: Step 1 - MainBranch Checkout
        if: steps.check.outputs.triggered == 'true'
        uses: actions/checkout@v2
     
      - name: Step 2 - JDK SETUP
        if: steps.check.outputs.triggered == 'true'
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'      
      
      - name: Set up Maven
        if: steps.check.outputs.triggered == 'true'
        uses: stCarolas/setup-maven@v4
        with:
            maven-version: 3.8.1     
      - name: Run Test 
        id: matrix
        if: steps.check.outputs.triggered == 'true'
        run: |
          echo "::set-output name=test-job::false"  
          mvn test
          echo "::set-output name=test-job::true"  
          
          
  test:
    if: always()
    needs: [deploy] 
    runs-on: ubuntu-latest
    steps:
      - name: echo-jobs
        run: |
          echo ${{ github.event.label.name == 'do-not-merge/hold' }}
          echo ${{ needs.deploy.outputs.matrix  == 'true' }}
          
      - uses: mshick/add-pr-comment@v1
        if: ${{ github.event.label.name == 'do-not-merge/hold' }} && ${{ steps.test-job.outputs.matrix == 'true' }}
        with:
          message: |
            Maven Test Failed 
            /hold
          repo-token: ${{ secrets.NSLHB_TEST_TOKEN }}
          repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
          allow-repeats: true
      
      - uses: mshick/add-pr-comment@v1
        if: ${{ github.event.label.name != 'do-not-merge/hold' }} && ${{ steps.test-job.outputs.matrix == 'true' }}
        with:
          message: |
            Github actions Failed 
          repo-token: ${{ secrets.NSLHB_TEST_TOKEN }}
          repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
          allow-repeats: true
          
      - uses: mshick/add-pr-comment@v1
        if: ${{ github.event.label.name == 'do-not-merge/hold' }} && ${{ steps.test-job.outputs.matrix == 'true' }}
        with:
          message: |
            Maven Test Passes 
            /remove-hold
          repo-token: ${{ secrets.NSLHB_TEST_TOKEN }}
          repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
          allow-repeats: true    
          
      - uses: mshick/add-pr-comment@v1
        if: ${{ github.event.label.name != 'do-not-merge/hold' }} && ${{ steps.test-job.outputs.matrix == 'true' }}
        with:
          message: |
            Github actions Test Passes 
          repo-token: ${{ secrets.NSLHB_TEST_TOKEN }}
          repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
          allow-repeats: true      

            
