name: PROW-Test 

on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.html_url, '/pull/') && contains(github.event.comment.body, '/ok-to-test') 
    outputs:
      test: ${{ steps.matrix.outputs.test_matrix }}
    steps:
   #   - uses: khan/pull-request-comment-trigger@master
   #     with:
   #       trigger: '/ok-to-test'
   #       reaction: rocket
   #     env:
   #       GITHUB_TOKEN: '${{ secrets.NSLHB_TEST_TOKEN }}'
      - name: Step 1 - MainBranch Checkout
        uses: actions/checkout@v2
     
      - name: Step 2 - JDK SETUP
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'      
      
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
            maven-version: 3.8.1     
      - name: Run Test 
        id: matrix
        run: |
          echo "::set-output name=test_matrix::false"  
          mvn test         
          echo "::set-output name=test_matrix::true"  
         
          
          
  test:
    needs: [deploy] 
    runs-on: ubuntu-latest
    steps:
      - name: echo-jobs
        run: |
          echo "testing"
          echo ${{ github.event.label.name == 'do-not-merge/hold' }}
          echo ${{ needs.deploy.outputs.test  == 'true' }}
          
      - uses: mshick/add-pr-comment@v1
        if: ${{ github.event.label.name == 'do-not-merge/hold' &&  steps.test-job.outputs.matrix == 'true' }}
        with:
          message: |
            Maven Test Failed 
            /hold
          repo-token: ${{ secrets.NSLHB_TEST_TOKEN }}
          repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
          allow-repeats: true
      
      - uses: mshick/add-pr-comment@v1
        if: ${{ github.event.label.name != 'do-not-merge/hold'  && steps.test-job.outputs.matrix == 'true' }}
        with:
          message: |
            Github actions Failed 
          repo-token: ${{ secrets.NSLHB_TEST_TOKEN }}
          repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
          allow-repeats: true
          
      - uses: mshick/add-pr-comment@v1
        if: ${{ github.event.label.name == 'do-not-merge/hold'  &&  steps.test-job.outputs.matrix == 'true' }}
        with:
          message: |
            Maven Test Passes 
            /remove-hold
          repo-token: ${{ secrets.NSLHB_TEST_TOKEN }}
          repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
          allow-repeats: true    
          
      - uses: mshick/add-pr-comment@v1
        if: ${{ github.event.label.name != 'do-not-merge/hold'  &&  steps.test-job.outputs.matrix == 'true' }}
        with:
          message: |
            Github actions Test Passes 
          repo-token: ${{ secrets.NSLHB_TEST_TOKEN }}
          repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
          allow-repeats: true      

            
