
name: Testing

on:
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs: 
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Step 1 - MainBranch Checkout
        uses: actions/checkout@v2
     
      - name: Step 2 - JDK SETUP
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      
      - name: Step 3 - Get Info
        run: |
          echo Hello
          cd ~/.m2
          ls -la
      
      - name: Step 4 - Build with Maven
        run: mvn -B package --file pom.xml 
          
      - name: Step 5 - Set up a cache for Maven
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runnner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
          
